<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hopper.Core</AssemblyName>
    <RootNamespace>Hopper.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hopper.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.1.9" />
  </ItemGroup>

</Project>
