<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hopper.Rhino.Host</AssemblyName>
    <RootNamespace>Hopper.Rhino.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Hopper.Core/Hopper.Core.csproj" />
  </ItemGroup>

</Project>
